services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: user
      POSTGRES_DB: test
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8228:8080